theme: jekyll-theme-slate
title: Welcome to the history of Bryan Butler!
description: Stay a while, and listen! This section of the web is dedicated to my latest projects. If you're here to look at some of my history, I've made sure to organize the page into chronological order.
